global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['backend:80']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
